name: Deploy to Hub CDN on merge Master
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Auth GCloud
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCE_AUTH_JSON }}'

      - name: Upload CSS
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: 'dist'
          destination: 'squid-css'

